use crate::config::template::Config;

pub fn generate(config: &Config, _binary_path: &str) -> String {
    let home = std::env::var("HOME").unwrap_or_else(|_| "~".to_string());
    let mut out = String::new();

    out.push_str("# Generated by tmux-sessionbar -- regenerate with: tmux-sessionbar apply\n\n");

    // General settings
    out.push_str("# --- General ---\n");
    out.push_str("set -g default-terminal \"tmux-256color\"\n");
    out.push_str("set -g mouse on\n");
    out.push_str("set -g base-index 1\n");
    out.push_str("setw -g pane-base-index 1\n");
    out.push_str("set -g renumber-windows on\n");
    out.push_str("set -g escape-time 0\n");
    // When a session is destroyed (e.g. killing its last window/pane via the
    // window/session bar X button), switch the client to the next session
    // instead of detaching. Keeps the user inside tmux as long as any
    // session remains.
    out.push_str("set -g detach-on-destroy off\n");
    out.push_str(&format!(
        "set -g history-limit {}\n\n",
        config.general.history_limit
    ));

    // Status bar global
    out.push_str("# --- Status bar ---\n");
    out.push_str(&format!(
        "set -g status-interval {}\n",
        config.status.interval
    ));
    out.push_str("set -g status 5\n");
    out.push_str(&format!(
        "set -g status-position {}\n",
        config.status.position
    ));
    out.push_str(&format!(
        "set -g status-style \"bg={},fg={}\"\n",
        config.status.bg, config.status.fg
    ));
    out.push('\n');

    // Status left: set by hooks, initial placeholder
    out.push_str(&format!(
        "set -g status-left-length {}\n",
        config.status.left.length
    ));
    out.push_str("set -g status-left \"loading...\"\n\n");

    // Status right
    out.push_str(&format!(
        "set -g status-right-length {}\n",
        config.status.right.length
    ));
    let right = render_right_segment(&config.status.right.blocks, config);
    out.push_str(&format!("set -g status-right \"{right}\"\n\n"));

    // Window status
    out.push_str("# --- Window status ---\n");
    out.push_str(&format!(
        "setw -g window-status-format \"{}\"\n",
        tmux_fmt::conf_style(&config.status.fg, &config.status.bg, false, " #I:#W ")
    ));
    out.push_str(&format!(
        "setw -g window-status-current-format \"{}\"\n",
        tmux_fmt::conf_style(
            &config.blocks.session_list.active_fg,
            &config.blocks.session_list.active_bg,
            true,
            " #I:#W "
        )
    ));
    out.push('\n');

    // Pane border
    if config.pane_border.enabled {
        out.push_str("# --- Pane border ---\n");
        out.push_str("set -g pane-border-status top\n");
        let pb = &config.pane_border;
        // Active pane: bold with index + command + directory
        // Inactive pane: dim with index + command
        let home = std::env::var("HOME").expect("HOME environment variable must be set");
        // Use separate #{?} blocks to avoid commas inside #[style] being parsed as conditional separators
        let pane_id = "#{session_name}:#{window_index}.#{pane_index} #{pane_current_command}";
        let format = format!(
            "\
             #{{?pane_active,#[fg={abg} bold] {pane_id} #[fg={ifg} nobold]#{{s|{home}|~|:pane_current_path}} (#{{{pid}}})#[default],\
             #[fg={ifg}] {pane_id} #[default]\
             }}",
            pid = "pane_pid",
            abg = pb.active_bg,
            ifg = pb.inactive_fg,
            home = home,
        );
        out.push_str(&format!("set -g pane-border-format \"{format}\"\n"));
        out.push_str(&format!(
            "set -g pane-active-border-style \"fg={}\"\n",
            pb.active_bg
        ));
        out.push_str(&format!(
            "set -g pane-border-style \"fg={}\"\n",
            pb.inactive_fg
        ));
        out.push('\n');
    }

    // Keybindings
    if config.keybindings.session_switch {
        out.push_str("# --- Session switching ---\n");
        out.push_str("bind -n M-( switch-client -p\n");
        out.push_str("bind -n M-) switch-client -n\n");
        out.push_str("bind -n M-s choose-session\n\n");
    }

    if config.keybindings.pane_clear {
        out.push_str("# --- Pane clear ---\n");
        out.push_str("bind -n M-k send-keys -R \\; clear-history\n\n");
    }

    // Mouse click binding + windowbar hooks
    out.push_str("# --- Mouse click + windowbar hooks ---\n");
    out.push_str(&format!(
        "run-shell -b '{home}/.config/tmux-sessionbar/bin/tmux-windowbar apply'\n\n",
    ));

    // Hooks: update session list on session events
    out.push_str("# --- Hooks: update session list dynamically ---\n");
    let hook_cmd = format!(
        "run-shell -b '{home}/.config/tmux-sessionbar/bin/tmux-sessionbar render-status left'"
    );
    out.push_str(&format!(
        "set-hook -g client-session-changed \"{hook_cmd}\"\n"
    ));
    out.push_str(&format!("set-hook -g session-created \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-closed \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-renamed \"{hook_cmd}\"\n"));
    out.push('\n');

    // Run once on load to populate initial status (synchronous — no -b flag)
    let init_cmd = format!(
        "run-shell '{home}/.config/tmux-sessionbar/bin/tmux-sessionbar render-status left'"
    );
    out.push_str(&format!("{init_cmd}\n\n"));

    // Plugins from config.toml
    out.push_str("# --- Plugins (TPM) ---\n");
    out.push_str("set -g @plugin 'tmux-plugins/tpm'\n");
    for plugin in &config.plugins {
        if plugin.enabled.unwrap_or(true) {
            out.push_str(&format!("set -g @plugin '{}'\n", plugin.name));
            for opt in &plugin.options {
                out.push_str(&format!("set -g {opt}\n"));
            }
        }
    }
    out.push_str("\n# TPM init (must be last)\n");
    out.push_str("run '~/.tmux/plugins/tpm/tpm'\n");

    out
}

fn render_right_segment(blocks: &[String], config: &Config) -> String {
    let mut parts = Vec::new();

    for block in blocks {
        match block.as_str() {
            "hostname" => {
                parts.push(tmux_fmt::conf_style(
                    &config.blocks.hostname.fg,
                    &config.blocks.hostname.bg,
                    false,
                    &config.blocks.hostname.format,
                ));
            }
            "datetime" => {
                parts.push(tmux_fmt::conf_style(
                    &config.blocks.datetime.fg,
                    &config.blocks.datetime.bg,
                    false,
                    &config.blocks.datetime.format,
                ));
            }
            _ => {
                parts.push(format!("{} {block} ", tmux_fmt::RESET));
            }
        }
    }

    parts.join("")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::template::default_config;

    fn make(config: &Config) -> String {
        generate(config, "/usr/local/bin/tmux-sessionbar")
    }

    #[test]
    fn status_is_enabled() {
        let out = make(&default_config());
        assert!(
            out.contains("set -g status 5\n"),
            "should set status to 5 lines"
        );
    }

    #[test]
    fn initial_render_is_synchronous() {
        let out = make(&default_config());
        let init_line = out
            .lines()
            .filter(|l| l.starts_with("run-shell '"))
            .find(|l| l.contains("render-status left"));
        assert!(init_line.is_some(), "initial render-status line must exist");
        assert!(
            !init_line.unwrap().contains("-b"),
            "initial render must be synchronous (no -b flag)"
        );
    }

    #[test]
    fn hooks_remain_async() {
        let out = make(&default_config());
        for hook in &[
            "client-session-changed",
            "session-created",
            "session-closed",
            "session-renamed",
        ] {
            let hook_line = out
                .lines()
                .find(|l| l.contains(&format!("set-hook -g {hook}")))
                .unwrap_or_else(|| panic!("hook {hook} must be present"));
            assert!(
                hook_line.contains("run-shell -b"),
                "hook {hook} must use async -b flag"
            );
        }
    }

    #[test]
    fn uses_correct_binary_path() {
        let home = std::env::var("HOME").unwrap_or_else(|_| "~".to_string());
        let custom = "/opt/bin/my-sessionbar";
        let out = generate(&default_config(), custom);
        assert!(out.contains(&format!(
            "run-shell '{home}/.config/tmux-sessionbar/bin/tmux-sessionbar render-status left'"
        )));
        assert!(out.contains(&format!(
            "run-shell -b '{home}/.config/tmux-sessionbar/bin/tmux-sessionbar render-status left'"
        )));
        assert!(!out.contains(custom));
    }

    #[test]
    fn windowbar_apply_uses_path_lookup() {
        let home = std::env::var("HOME").unwrap_or_else(|_| "~".to_string());
        let out = make(&default_config());
        assert!(out.contains(&format!(
            "run-shell -b '{home}/.config/tmux-sessionbar/bin/tmux-windowbar apply'"
        )));
        assert!(!out.contains("/usr/local/bin/tmux-windowbar"));
    }

    #[test]
    fn disabled_plugin_excluded() {
        let mut config = default_config();
        config.plugins.iter_mut().for_each(|p| {
            if p.name == "fcsonline/tmux-thumbs" {
                p.enabled = Some(false);
            }
        });
        let out = make(&config);
        assert!(!out.contains("fcsonline/tmux-thumbs"));
    }

    #[test]
    fn keybindings_toggle() {
        let mut config = default_config();
        config.keybindings.session_switch = false;
        config.keybindings.pane_clear = false;
        let out = make(&config);
        assert!(!out.contains("bind -n M-("));
        assert!(!out.contains("bind -n M-k"));
    }

    #[test]
    fn right_segment_renders_blocks() {
        let out = make(&default_config());
        assert!(out.contains("#H"), "hostname block should contain #H");
        assert!(out.contains("%H:%M"), "datetime block should contain %H:%M");
    }

    // ── detach-on-destroy defensive suite ─────────────────────────────────
    //
    // Closing the last window or last pane via the bar X button destroys the
    // enclosing session. tmux's default (`detach-on-destroy on`) detaches the
    // client when that happens — kicking the user fully out of tmux. We emit
    // `set -g detach-on-destroy off` so tmux switches to another session
    // instead. These tests lock that behavior in against regressions.

    /// Helper: count exact-line occurrences in generated output.
    fn count_lines(haystack: &str, needle: &str) -> usize {
        haystack.lines().filter(|l| l.trim() == needle).count()
    }

    #[test]
    fn detach_on_destroy_off_is_emitted() {
        let out = make(&default_config());
        assert!(
            out.contains("set -g detach-on-destroy off"),
            "generated tmux.conf must set detach-on-destroy off so killing the \
             last window/pane switches session instead of detaching the client;\n\
             got:\n{out}"
        );
    }

    #[test]
    fn detach_on_destroy_value_is_off_not_on() {
        let out = make(&default_config());
        // `contains` is substring-based, so an accidental "detach-on-destroy on"
        // would not be caught by the positive test above. Assert explicitly.
        assert!(
            !out.contains("set -g detach-on-destroy on"),
            "must not emit `detach-on-destroy on` — that reverts to the \
             tmux default and kicks users out on last-window kill"
        );
        for alt in ["no-detached", "\"off\"", "'off'"] {
            assert!(
                !out.contains(&format!("set -g detach-on-destroy {alt}")),
                "unexpected detach-on-destroy value `{alt}` in output"
            );
        }
    }

    #[test]
    fn detach_on_destroy_emitted_exactly_once() {
        let out = make(&default_config());
        let n = count_lines(&out, "set -g detach-on-destroy off");
        assert_eq!(
            n, 1,
            "detach-on-destroy should appear exactly once, got {n} occurrences;\n\
             duplicates indicate a merge/copy-paste regression in generate()"
        );
    }

    #[test]
    fn detach_on_destroy_is_global_not_window_local() {
        let out = make(&default_config());
        // tmux accepts `setw -g detach-on-destroy` silently for unknown scope
        // but the correct scope is session-level via `set -g`.
        assert!(
            !out.contains("setw -g detach-on-destroy"),
            "detach-on-destroy is a session option — must use `set -g`, not `setw`"
        );
        assert!(
            !out.contains("set-option -w detach-on-destroy"),
            "detach-on-destroy is a session option — window scope is wrong"
        );
    }

    #[test]
    fn detach_on_destroy_lives_in_general_section() {
        let out = make(&default_config());
        let general_marker = out
            .find("# --- General ---")
            .expect("General section header must exist");
        let statusbar_marker = out
            .find("# --- Status bar ---")
            .expect("Status bar section header must exist");
        let detach_pos = out
            .find("set -g detach-on-destroy off")
            .expect("detach-on-destroy line must exist");
        assert!(
            detach_pos > general_marker && detach_pos < statusbar_marker,
            "detach-on-destroy must live inside the General section \
             (between General header at {general_marker} and Status bar \
             header at {statusbar_marker}); found at {detach_pos}"
        );
    }

    #[test]
    fn detach_on_destroy_applied_before_plugins() {
        // tmux-resurrect restores sessions on startup. The detach-on-destroy
        // setting must be applied *before* plugins run so the behavior is
        // in effect immediately after restore.
        let out = make(&default_config());
        let detach_pos = out
            .find("set -g detach-on-destroy off")
            .expect("detach-on-destroy line must exist");
        let plugin_marker = out
            .find("# --- Plugins (TPM) ---")
            .expect("Plugins section must exist");
        let tpm_init = out
            .find("run '~/.tmux/plugins/tpm/tpm'")
            .expect("TPM init line must exist");
        assert!(
            detach_pos < plugin_marker,
            "detach-on-destroy must be set before plugin declarations"
        );
        assert!(
            detach_pos < tpm_init,
            "detach-on-destroy must be set before TPM init so restored \
             sessions inherit the option"
        );
    }

    #[test]
    fn detach_on_destroy_survives_custom_toml_config() {
        // Same user-supplied TOML as the existing config_roundtrip test.
        // Verify that *user* config cannot accidentally strip the
        // detach-on-destroy guarantee — it is hardcoded in generate().
        let toml_str = concat!(
            "[general]\n",
            "history_limit = 10000\n",
            "\n",
            "[status]\n",
            "interval = 5\n",
            "position = \"bottom\"\n",
            "bg = \"#000000\"\n",
            "fg = \"#ffffff\"\n",
            "\n",
            "[status.left]\n",
            "blocks = [\"session-list\"]\n",
            "length = 200\n",
            "\n",
            "[status.right]\n",
            "blocks = [\"hostname\"]\n",
            "length = 40\n",
            "\n",
            "[blocks.session-list]\n",
            "active_fg = \"#000\"\n",
            "active_bg = \"#fff\"\n",
            "inactive_fg = \"#aaa\"\n",
            "inactive_bg = \"#333\"\n",
            "separator = \"|\"\n",
            "show_new_button = false\n",
            "show_kill_button = false\n",
            "button_fg = \"#000\"\n",
            "button_bg = \"#fff\"\n",
            "kill_bg = \"#f00\"\n",
            "\n",
            "[blocks.hostname]\n",
            "fg = \"#000\"\n",
            "bg = \"#0ff\"\n",
            "format = \" HOST \"\n",
            "\n",
            "[keybindings]\n",
            "session_switch = false\n",
            "pane_clear = false\n",
        );
        let config: Config = toml::from_str(toml_str).expect("valid toml");
        let out = make(&config);
        assert!(
            out.contains("set -g detach-on-destroy off"),
            "user TOML must never suppress detach-on-destroy off"
        );
    }

    #[test]
    fn detach_on_destroy_stable_across_plugin_toggles() {
        // Disabling plugins must not remove the detach-on-destroy line.
        let mut config = default_config();
        config.plugins.iter_mut().for_each(|p| {
            p.enabled = Some(false);
        });
        let out = make(&config);
        assert!(
            out.contains("set -g detach-on-destroy off"),
            "detach-on-destroy must survive even with all plugins disabled"
        );
    }

    #[test]
    fn detach_on_destroy_stable_across_keybinding_toggles() {
        let mut config = default_config();
        config.keybindings.session_switch = false;
        config.keybindings.pane_clear = false;
        let out = make(&config);
        assert!(
            out.contains("set -g detach-on-destroy off"),
            "detach-on-destroy must survive keybinding toggles"
        );
    }

    #[test]
    fn detach_on_destroy_line_is_well_formed() {
        // Guard against subtle typos in the literal string (dashes, spacing,
        // quoting). tmux silently ignores unknown options and would leave the
        // default `on` in effect — a silent regression we must not ship.
        let out = make(&default_config());
        let line = out
            .lines()
            .find(|l| l.contains("detach-on-destroy"))
            .expect("detach-on-destroy line must exist");
        assert_eq!(
            line.trim(),
            "set -g detach-on-destroy off",
            "line must be the exact literal tmux expects; any deviation \
             (extra quotes, wrong dashes, stray whitespace) will be parsed \
             as an unknown option and silently ignored by tmux"
        );
    }

    #[test]
    fn detach_on_destroy_not_inside_comment() {
        // Make sure no future refactor accidentally moves the setting onto
        // a commented-out line.
        let out = make(&default_config());
        for line in out.lines() {
            if line.contains("detach-on-destroy") {
                let trimmed = line.trim_start();
                assert!(
                    !trimmed.starts_with('#'),
                    "detach-on-destroy must not live on a comment line:\n  {line}"
                );
            }
        }
    }

    #[test]
    fn config_roundtrip_from_toml() {
        let toml_str = concat!(
            "[general]\n",
            "history_limit = 10000\n",
            "\n",
            "[status]\n",
            "interval = 5\n",
            "position = \"bottom\"\n",
            "bg = \"#000000\"\n",
            "fg = \"#ffffff\"\n",
            "\n",
            "[status.left]\n",
            "blocks = [\"session-list\"]\n",
            "length = 200\n",
            "\n",
            "[status.right]\n",
            "blocks = [\"hostname\"]\n",
            "length = 40\n",
            "\n",
            "[blocks.session-list]\n",
            "active_fg = \"#000\"\n",
            "active_bg = \"#fff\"\n",
            "inactive_fg = \"#aaa\"\n",
            "inactive_bg = \"#333\"\n",
            "separator = \"|\"\n",
            "show_new_button = false\n",
            "show_kill_button = false\n",
            "button_fg = \"#000\"\n",
            "button_bg = \"#fff\"\n",
            "kill_bg = \"#f00\"\n",
            "\n",
            "[blocks.hostname]\n",
            "fg = \"#000\"\n",
            "bg = \"#0ff\"\n",
            "format = \" HOST \"\n",
            "\n",
            "[keybindings]\n",
            "session_switch = false\n",
            "pane_clear = false\n",
        );
        let config: Config = toml::from_str(toml_str).expect("valid toml");
        let out = make(&config);
        assert!(out.contains("set -g status-interval 5\n"));
        assert!(out.contains("set -g status-position bottom\n"));
        assert!(out.contains("set -g history-limit 10000\n"));
        assert!(out.contains("set -g status-left-length 200\n"));
        assert!(!out.contains("bind -n M-("));
    }
}
