use crate::config::template::Config;

pub fn generate(config: &Config, binary_path: &str) -> String {
    let mut out = String::new();

    out.push_str("# Generated by tmux-sessionbar -- regenerate with: tmux-sessionbar apply\n\n");

    // General settings
    out.push_str("# --- General ---\n");
    out.push_str("set -g default-terminal \"tmux-256color\"\n");
    out.push_str("set -g mouse on\n");
    out.push_str("set -g base-index 1\n");
    out.push_str("setw -g pane-base-index 1\n");
    out.push_str("set -g renumber-windows on\n");
    out.push_str("set -g escape-time 0\n\n");

    // Status bar global
    out.push_str("# --- Status bar ---\n");
    out.push_str(&format!("set -g status-interval {}\n", config.status.interval));
    out.push_str("set -g status on\n");
    out.push_str(&format!("set -g status-position {}\n", config.status.position));
    out.push_str(&format!(
        "set -g status-style \"bg={},fg={}\"\n",
        config.status.bg, config.status.fg
    ));
    out.push('\n');

    // Status left: set by hooks, initial placeholder
    out.push_str(&format!(
        "set -g status-left-length {}\n",
        config.status.left.length
    ));
    out.push_str("set -g status-left \"loading...\"\n\n");

    // Status right
    out.push_str(&format!(
        "set -g status-right-length {}\n",
        config.status.right.length
    ));
    let right = render_right_segment(&config.status.right.blocks, config);
    out.push_str(&format!("set -g status-right \"{right}\"\n\n"));

    // Window status
    out.push_str("# --- Window status ---\n");
    out.push_str(&format!(
        "setw -g window-status-format \"#[fg={},bg={}] #I:#W \"\n",
        config.status.fg, config.status.bg
    ));
    out.push_str(&format!(
        "setw -g window-status-current-format \"#[fg={},bg={},bold] #I:#W \"\n",
        config.blocks.session_list.active_fg, config.blocks.session_list.active_bg
    ));
    out.push('\n');

    // Keybindings
    if config.keybindings.session_switch {
        out.push_str("# --- Session switching ---\n");
        out.push_str("bind -n M-( switch-client -p\n");
        out.push_str("bind -n M-) switch-client -n\n");
        out.push_str("bind -n M-s choose-session\n\n");
    }

    // Mouse click binding is managed by tmux-windowbar apply
    // (includes click-handler chain + confirm-before support)

    // Hooks: update session list on session events
    out.push_str("# --- Hooks: update session list dynamically ---\n");
    let hook_cmd = format!("run-shell -b '{binary_path} render-status left'");
    out.push_str(&format!("set-hook -g client-session-changed \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-created \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-closed \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-renamed \"{hook_cmd}\"\n"));
    out.push('\n');

    // Run once on load to populate initial status
    out.push_str(&format!("{hook_cmd}\n\n"));

    // TPM + session persistence plugins
    out.push_str("# --- Plugins (TPM) ---\n");
    out.push_str("set -g @plugin 'tmux-plugins/tpm'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-resurrect'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-continuum'\n");
    out.push_str("set -g @continuum-restore 'on'\n");
    out.push_str("set -g @continuum-save-interval '15'\n");
    out.push_str("set -g @resurrect-capture-pane-contents 'on'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-yank'\n");
    out.push_str("set -g @plugin 'Morantron/tmux-fingers'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-open'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-logging'\n");
    out.push_str("set -g @plugin 'tmux-plugins/tmux-sensible'\n");
    out.push_str("set -g @plugin 'rickstaa/tmux-notify'\n");
    out.push_str("set -g @plugin 'jaclu/tmux-menus'\n\n");
    out.push_str("# TPM init (must be last)\n");
    out.push_str("run '~/.tmux/plugins/tpm/tpm'\n");

    out
}

fn render_right_segment(blocks: &[String], config: &Config) -> String {
    let mut parts = Vec::new();

    for block in blocks {
        match block.as_str() {
            "hostname" => {
                parts.push(format!(
                    "#[fg={},bg={}]{}",
                    config.blocks.hostname.fg,
                    config.blocks.hostname.bg,
                    config.blocks.hostname.format
                ));
            }
            "datetime" => {
                parts.push(format!(
                    "#[fg={},bg={}]{}",
                    config.blocks.datetime.fg,
                    config.blocks.datetime.bg,
                    config.blocks.datetime.format
                ));
            }
            _ => {
                parts.push(format!("#[default] {block} "));
            }
        }
    }

    parts.join("")
}
