use crate::config::template::Config;

pub fn generate(config: &Config, binary_path: &str) -> String {
    let mut out = String::new();

    out.push_str("# Generated by tmux-sessionbar -- regenerate with: tmux-sessionbar apply\n\n");

    // General settings
    out.push_str("# --- General ---\n");
    out.push_str("set -g default-terminal \"tmux-256color\"\n");
    out.push_str("set -g mouse on\n");
    out.push_str("set -g base-index 1\n");
    out.push_str("setw -g pane-base-index 1\n");
    out.push_str("set -g renumber-windows on\n");
    out.push_str("set -g escape-time 0\n");
    out.push_str(&format!("set -g history-limit {}\n\n", config.general.history_limit));

    // Status bar global
    out.push_str("# --- Status bar ---\n");
    out.push_str(&format!("set -g status-interval {}\n", config.status.interval));
    out.push_str("set -g status 5\n");
    out.push_str(&format!("set -g status-position {}\n", config.status.position));
    out.push_str(&format!(
        "set -g status-style \"bg={},fg={}\"\n",
        config.status.bg, config.status.fg
    ));
    out.push('\n');

    // Status left: set by hooks, initial placeholder
    out.push_str(&format!(
        "set -g status-left-length {}\n",
        config.status.left.length
    ));
    out.push_str("set -g status-left \"loading...\"\n\n");

    // Status right
    out.push_str(&format!(
        "set -g status-right-length {}\n",
        config.status.right.length
    ));
    let right = render_right_segment(&config.status.right.blocks, config);
    out.push_str(&format!("set -g status-right \"{right}\"\n\n"));

    // Window status
    out.push_str("# --- Window status ---\n");
    out.push_str(&format!(
        "setw -g window-status-format \"{}\"\n",
        tmux_fmt::conf_style(&config.status.fg, &config.status.bg, false, " #I:#W ")
    ));
    out.push_str(&format!(
        "setw -g window-status-current-format \"{}\"\n",
        tmux_fmt::conf_style(&config.blocks.session_list.active_fg, &config.blocks.session_list.active_bg, true, " #I:#W ")
    ));
    out.push('\n');

    // Keybindings
    if config.keybindings.session_switch {
        out.push_str("# --- Session switching ---\n");
        out.push_str("bind -n M-( switch-client -p\n");
        out.push_str("bind -n M-) switch-client -n\n");
        out.push_str("bind -n M-s choose-session\n\n");
    }

    if config.keybindings.pane_clear {
        out.push_str("# --- Pane clear ---\n");
        out.push_str("bind -n M-k send-keys -R \\; clear-history\n\n");
    }

    // Mouse click binding + windowbar hooks
    out.push_str("# --- Mouse click + windowbar hooks ---\n");
    out.push_str("run-shell -b '/usr/local/bin/tmux-windowbar apply'\n\n");

    // Hooks: update session list on session events
    out.push_str("# --- Hooks: update session list dynamically ---\n");
    let hook_cmd = format!("run-shell -b '{binary_path} render-status left'");
    out.push_str(&format!("set-hook -g client-session-changed \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-created \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-closed \"{hook_cmd}\"\n"));
    out.push_str(&format!("set-hook -g session-renamed \"{hook_cmd}\"\n"));
    out.push('\n');

    // Run once on load to populate initial status (synchronous — no -b flag)
    let init_cmd = format!("run-shell '{binary_path} render-status left'");
    out.push_str(&format!("{init_cmd}\n\n"));

    // Plugins from config.toml
    out.push_str("# --- Plugins (TPM) ---\n");
    out.push_str("set -g @plugin 'tmux-plugins/tpm'\n");
    for plugin in &config.plugins {
        if plugin.enabled.unwrap_or(true) {
            out.push_str(&format!("set -g @plugin '{}'\n", plugin.name));
            for opt in &plugin.options {
                out.push_str(&format!("set -g {opt}\n"));
            }
        }
    }
    out.push_str("\n# TPM init (must be last)\n");
    out.push_str("run '~/.tmux/plugins/tpm/tpm'\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::template::default_config;

    fn make(config: &Config) -> String {
        generate(config, "/usr/local/bin/tmux-sessionbar")
    }

    #[test]
    fn status_is_enabled() {
        let out = make(&default_config());
        assert!(
            out.contains("set -g status 5\n"),
            "should set status to 5 lines"
        );
    }

    #[test]
    fn initial_render_is_synchronous() {
        let out = make(&default_config());
        let init_line = out
            .lines()
            .filter(|l| l.starts_with("run-shell '"))
            .find(|l| l.contains("render-status left"));
        assert!(init_line.is_some(), "initial render-status line must exist");
        assert!(
            !init_line.unwrap().contains("-b"),
            "initial render must be synchronous (no -b flag)"
        );
    }

    #[test]
    fn hooks_remain_async() {
        let out = make(&default_config());
        for hook in &[
            "client-session-changed",
            "session-created",
            "session-closed",
            "session-renamed",
        ] {
            let hook_line = out
                .lines()
                .find(|l| l.contains(&format!("set-hook -g {hook}")))
                .unwrap_or_else(|| panic!("hook {hook} must be present"));
            assert!(
                hook_line.contains("run-shell -b"),
                "hook {hook} must use async -b flag"
            );
        }
    }

    #[test]
    fn uses_correct_binary_path() {
        let custom = "/opt/bin/my-sessionbar";
        let out = generate(&default_config(), custom);
        assert!(out.contains(&format!("run-shell '{custom} render-status left'")));
        assert!(out.contains(&format!("run-shell -b '{custom} render-status left'")));
    }

    #[test]
    fn disabled_plugin_excluded() {
        let mut config = default_config();
        config.plugins.iter_mut().for_each(|p| {
            if p.name == "fcsonline/tmux-thumbs" {
                p.enabled = Some(false);
            }
        });
        let out = make(&config);
        assert!(!out.contains("fcsonline/tmux-thumbs"));
    }

    #[test]
    fn keybindings_toggle() {
        let mut config = default_config();
        config.keybindings.session_switch = false;
        config.keybindings.pane_clear = false;
        let out = make(&config);
        assert!(!out.contains("bind -n M-("));
        assert!(!out.contains("bind -n M-k"));
    }

    #[test]
    fn right_segment_renders_blocks() {
        let out = make(&default_config());
        assert!(out.contains("#H"), "hostname block should contain #H");
        assert!(out.contains("%H:%M"), "datetime block should contain %H:%M");
    }

    #[test]
    fn config_roundtrip_from_toml() {
        let toml_str = concat!(
            "[general]\n",
            "history_limit = 10000\n",
            "\n",
            "[status]\n",
            "interval = 5\n",
            "position = \"bottom\"\n",
            "bg = \"#000000\"\n",
            "fg = \"#ffffff\"\n",
            "\n",
            "[status.left]\n",
            "blocks = [\"session-list\"]\n",
            "length = 200\n",
            "\n",
            "[status.right]\n",
            "blocks = [\"hostname\"]\n",
            "length = 40\n",
            "\n",
            "[blocks.session-list]\n",
            "active_fg = \"#000\"\n",
            "active_bg = \"#fff\"\n",
            "inactive_fg = \"#aaa\"\n",
            "inactive_bg = \"#333\"\n",
            "separator = \"|\"\n",
            "show_new_button = false\n",
            "show_kill_button = false\n",
            "button_fg = \"#000\"\n",
            "button_bg = \"#fff\"\n",
            "kill_bg = \"#f00\"\n",
            "\n",
            "[blocks.hostname]\n",
            "fg = \"#000\"\n",
            "bg = \"#0ff\"\n",
            "format = \" HOST \"\n",
            "\n",
            "[keybindings]\n",
            "session_switch = false\n",
            "pane_clear = false\n",
        );
        let config: Config = toml::from_str(toml_str).expect("valid toml");
        let out = make(&config);
        assert!(out.contains("set -g status-interval 5\n"));
        assert!(out.contains("set -g status-position bottom\n"));
        assert!(out.contains("set -g history-limit 10000\n"));
        assert!(out.contains("set -g status-left-length 200\n"));
        assert!(!out.contains("bind -n M-("));
    }
}

fn render_right_segment(blocks: &[String], config: &Config) -> String {
    let mut parts = Vec::new();

    for block in blocks {
        match block.as_str() {
            "hostname" => {
                parts.push(tmux_fmt::conf_style(
                    &config.blocks.hostname.fg,
                    &config.blocks.hostname.bg,
                    false,
                    &config.blocks.hostname.format,
                ));
            }
            "datetime" => {
                parts.push(tmux_fmt::conf_style(
                    &config.blocks.datetime.fg,
                    &config.blocks.datetime.bg,
                    false,
                    &config.blocks.datetime.format,
                ));
            }
            _ => {
                parts.push(format!("{} {block} ", tmux_fmt::RESET));
            }
        }
    }

    parts.join("")
}
