use crate::config::template;
use std::path::PathBuf;
use std::process::Command;

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let home = home_dir();
    let tmux_conf_path = home.join(".tmux.conf");
    let config_path = template::config_path();

    // Config state
    println!("=== tmux-sessionbar status ===\n");

    if config_path.exists() {
        println!("config: {} (ok)", config_path.display());
    } else {
        println!("config: not found (run `tmux-sessionbar init`)");
    }

    if tmux_conf_path.exists() {
        let content = std::fs::read_to_string(&tmux_conf_path).unwrap_or_default();
        if content.contains("Generated by tmux-sessionbar") {
            println!(".tmux.conf: managed by tmux-sessionbar");
        } else {
            println!(".tmux.conf: exists but NOT managed by tmux-sessionbar");
        }
    } else {
        println!(".tmux.conf: not found");
    }

    // Binary path
    if let Ok(exe) = std::env::current_exe() {
        println!("binary: {}", exe.display());
    }

    // tmux sessions
    println!();
    let output = Command::new("tmux")
        .args(["list-sessions"])
        .output();

    match output {
        Ok(o) if o.status.success() => {
            let sessions = String::from_utf8_lossy(&o.stdout);
            println!("sessions:");
            for line in sessions.lines() {
                println!("  {line}");
            }
        }
        _ => {
            println!("tmux: not running");
        }
    }

    Ok(())
}

fn home_dir() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/root".into()))
}
