use crate::config::template;
use anyhow::Result;
use std::path::PathBuf;

pub fn run() -> Result<()> {
    let home = home_dir();
    let tmux_conf_path = home.join(".tmux.conf");
    let config_path = template::config_path();

    println!("=== tmux-sessionbar status ===\n");

    if config_path.exists() {
        println!("config: {} (ok)", config_path.display());
    } else {
        println!("config: not found (run `tmux-sessionbar init`)");
    }

    if tmux_conf_path.exists() {
        let content = std::fs::read_to_string(&tmux_conf_path).unwrap_or_default();
        if content.contains("Generated by tmux-sessionbar") {
            println!(".tmux.conf: managed by tmux-sessionbar");
        } else {
            println!(".tmux.conf: exists but NOT managed by tmux-sessionbar");
        }
    } else {
        println!(".tmux.conf: not found");
    }

    if let Ok(exe) = std::env::current_exe() {
        println!("binary: {}", exe.display());
    }

    println!();
    match tmux_fmt::tmux::query(&["list-sessions"]) {
        Ok(sessions) => {
            println!("sessions:");
            for line in sessions.lines() {
                println!("  {line}");
            }
        }
        Err(_) => println!("tmux: not running"),
    }

    Ok(())
}

fn home_dir() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/root".into())) // LINT_ALLOW: last-resort fallback when $HOME is unset
}
